
name: Playwright (Azure Playwright Workspaces)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write        # for OIDC to Azure
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_SERVICE_URL: ${{ secrets.PLAYWRIGHT_SERVICE_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers (local tooling)
        run: npx playwright install --with-deps

      # Authenticate the workflow to Azure using OIDC (recommended)
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run Playwright tests on Azure cloud browsers
        run: |
          npx playwright test \
            --config=playwright.service.config.ts \
            --workers=20

      - name: Upload HTML report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
